//this is an auto-generated bug report
//package name: de.k4ever.k4android
//version: 1.3
//appro_time: 13
 FATAL EXCEPTION: AsyncTask #1
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NullPointerException
 	at com.android.volley.Request.<init>(Request.java:137)
 	at com.android.volley.toolbox.JsonRequest.<init>(JsonRequest.java:58)
 	at com.android.volley.toolbox.JsonArrayRequest.<init>(JsonArrayRequest.java:42)
 	at de.k4ever.k4android.database.KassenUpdateDatasets$3.<init>(KassenUpdateDatasets.java:80)
 	at de.k4ever.k4android.database.KassenUpdateDatasets.doInBackground(KassenUpdateDatasets.java:54)
 	at de.k4ever.k4android.database.KassenUpdateDatasets.doInBackground(KassenUpdateDatasets.java:31)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 	... 4 more
