//this is an auto-generated bug report
//package name: it.reyboz.bustorino
//version: 1.8.5
//appro_time: 135
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/data/it.reyboz.bustorino/databases/user.db
 	at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1156)
 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
 	at it.reyboz.bustorino.middleware.UserDB.getFavorites(UserDB.java:177)
 	at it.reyboz.bustorino.ActivityFavorites$AsyncGetFavorites.doInBackground(ActivityFavorites.java:203)
 	at it.reyboz.bustorino.ActivityFavorites$AsyncGetFavorites.doInBackground(ActivityFavorites.java:190)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
