//this is an auto-generated bug report
//package name: com.example.sshtry
//version: 1.0
//appro_time: 108
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NumberFormatException: Invalid int: "m3ob"
 	at java.lang.Integer.invalidInt(Integer.java:138)
 	at java.lang.Integer.parse(Integer.java:375)
 	at java.lang.Integer.parseInt(Integer.java:366)
 	at java.lang.Integer.parseInt(Integer.java:332)
 	at com.example.sshtry.MyConnect.doInBackground(MyConnect.java:43)
 	at com.example.sshtry.MyConnect.doInBackground(MyConnect.java:23)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
