//this is an auto-generated bug report
//package name: org.smssecure.smssecure
//version: 0.15.1
//appro_time: 170
 java.lang.RuntimeException: An error occured while executing doInBackground()
 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 	at java.lang.Thread.run(Thread.java:841)
 Caused by: java.lang.NullPointerException
 	at org.smssecure.smssecure.recipients.RecipientFactory.getRecipientsFor(RecipientFactory.java:48)
 	at org.smssecure.smssecure.database.MmsAddressDatabase.getRecipientsForId(MmsAddressDatabase.java:138)
 	at org.smssecure.smssecure.MessageDetailsActivity$MessageRecipientAsyncTask.doInBackground(MessageDetailsActivity.java:320)
 	at org.smssecure.smssecure.MessageDetailsActivity$MessageRecipientAsyncTask.doInBackground(MessageDetailsActivity.java:290)
 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
